# Generated by Django 4.0.8 on 2022-12-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smecustomuser',
            name='SME_Email',
        ),
        migrations.RemoveField(
            model_name='smecustomuser',
            name='SME_UserName',
        ),
    ]
