# Generated by Django 4.0.8 on 2022-12-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useraccounts', '0002_remove_smecustomuser_sme_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smecustomuser',
            name='SME_Name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
