# Generated by Django 4.0.8 on 2022-12-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('Category', models.CharField(choices=[('Perishables', 'Perishables'), ('Electronics', 'Electronics'), ('Stationary', 'Stationary')], max_length=70, null=True)),
                ('Quantity', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
